### PR TITLE
Extend unit tests for better coverage of mon-init.c.

### PR DESCRIPTION
**Pull request by backwardsEric**

### CODE REVIEW

**Comment by backwardsEric** [comment]
The forced push fixed the compilation error introduced by https://github.com/angband/angband/pull/5459 .

**Comment by backwardsEric** [comment]
And another forced push to add two missing lines.  Maybe next time I won't pull something out of git stash and assume it was ready to go.
