### ISSUE TITLE
main-gcu.c compile errors

### ISSUE THREAD

**Issue by angband-import** [angband/angband#1243]
**Reported by Mangojuice on 12 Jan 2009 16:32 UTC**
I get several compile errors when trying to compile; I'm using Mac / Unix.  The compile errors were resolved when I removed the lines undefining/redefining "bool" and "term" in main-gcu.c.

main-gcu.c: In function 'Term_xtra_gcu_alive':
main-gcu.c:298: error: dereferencing pointer to incomplete type
main-gcu.c:298: error: dereferencing pointer to incomplete type
main-gcu.c:298: warning: left-hand operand of comma expression has no effect
main-gcu.c:298: warning: statement with no effect
main-gcu.c: In function 'Term_nuke_gcu':
main-gcu.c:391: error: dereferencing pointer to incomplete type
main-gcu.c:391: error: dereferencing pointer to incomplete type
main-gcu.c:391: warning: left-hand operand of comma expression has no effect
main-gcu.c:391: warning: statement with no effect
main-gcu.c: In function 'Term_xtra_gcu':
main-gcu.c:513: error: dereferencing pointer to incomplete type
main-gcu.c: In function 'Term_text_gcu':
main-gcu.c:625: error: dereferencing pointer to incomplete type
main-gcu.c:639: error: dereferencing pointer to incomplete type
main-gcu.c: In function 'init_gcu':
main-gcu.c:721: error: 'bool' undeclared (first use in this function)
main-gcu.c:721: error: (Each undeclared identifier is reported only once
main-gcu.c:721: error: for each function it appears in.)
main-gcu.c:721: error: parse error before "use_big_screen"
main-gcu.c:729: error: 'use_big_screen' undeclared (first use in this function)

**Comment by angband-import** [comment]
**Modified by takkaria on 13 Jan 2009 13:01 UTC**

**Comment by angband-import** [comment]
**Modified by takkaria on 21 Jan 2009 23:24 UTC**

**Comment by angband-import** [comment]
**Comment by takkaria on 21 Jan 2009 23:25 UTC**
What version of OS X are you on?  This works fine here on 10.5.6.

**Comment by angband-import** [comment]
**Comment by takkaria on 25 Jan 2009 12:35 UTC**
The #undef bool is causing this; removing it works on 10.4.  10.5 works equally well either way; need to test to see if modern BSDs/Linux can deal with that as well.

**Comment by angband-import** [comment]
**Comment by takkaria on 25 Jan 2009 19:06 UTC**
in [fd01a49] (SVN r1177)
